### ISSUE TITLE
Фидбек 

### ISSUE THREAD

**Issue by Nurjigit-Melis-uulu** [aizadazh/Casablanca#1]
1) криво. Исползуй флекс бокс.
![image](https://user-images.githubusercontent.com/45354207/62770131-2e9a6880-babc-11e9-8241-7857904c033a.png)

2) Не красиво и не работает
![image](https://user-images.githubusercontent.com/45354207/62770209-57baf900-babc-11e9-9c9c-89514450559e.png)

3) В макете он был растянутым до конца.
![image](https://user-images.githubusercontent.com/45354207/62770348-af596480-babc-11e9-87d8-d773a82ed0f5.png)

4) Снова криво.
![image](https://user-images.githubusercontent.com/45354207/62770494-fa737780-babc-11e9-8f3a-10f730c4985d.png)

совет: посмотрите про flex-box https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by damilurg** [comment]
первая секция должна быть 100vh
при нажатии на гамбургер, при нажатии на любую точку страницы - не схлопывается, перекрывается

**Comment by aizadazh** [comment]
Комментарии Нуржигита:
1. Закрыто - действительно нужно было флекс использовать, я почему то пошла по пути position absolute и задавала вручную координаты для каждого breakpoint - отсюда и все проблемы "криво". Много времени потеряла здесь выравнивая адаптивность.
2. Переделала полностью. Все работает. Сделала ховер эффект.
3. Переделала.
4. Слайдер попробовала выровнять.
Комментарии Тимура:
1. Сделала 100vh  - скролл также переделала
2. Пока не получается - плохо знаю js
3-17 пункты - переделала.
